### ISSUE TITLE
Some values for sell prices are missing

### ISSUE THREAD

**Issue by dentou** [a11to1n3/M5Accuracy#3]
The sell price dataset does not contains all the values for the variable "wm_yr_wk" included in the calendar dataset corresponding to the dates in sales_train_validation dataset. Merging results in null values.

**Comment by a11to1n3** [comment]
could you reproduce it? As last time I checked from the finally merged DataFrame, there is not NULL values there ❓

**Comment by dentou** [comment]
You will see that if you use the function merge() with argument how="left", which uses the keys from the sales_train_validation data frame. I have done that in the PR.

**Comment by dentou** [comment]
You can also do these queries manually:
`print(sp_df[(sp_df["store_id"]=="CA_1") & (sp_df["item_id"]=="HOBBIES_1_045") & (sp_df["wm_yr_wk"]==11415)])`
`print(calendar_df[calendar_df["wm_yr_wk"]==11415])`
`print(stv_df.loc[(stv_df["store_id"]=="CA_1") & (stv_df["item_id"]=="HOBBIES_1_045"), :"d_1204"])`
Notes: `sp`, `calendar` and `stv` are the sell prices, calendar and sales_train_validation data frames, resp.
